### ISSUE TITLE
debbug "the hindu" section

### ISSUE THREAD

**Issue by s-pratyush** [Pratyush-Saxena/NewsAggregator#7]
the hindu section is not showing any news

**Comment by jphetphoumy** [comment]
Hello, I'd like to help you on this issue !

**Comment by s-pratyush** [comment]
Hey @jphetphoumy....yes pls go ahead

**Comment by jphetphoumy** [comment]
@Pratyush-Saxena I will make a PR for this issue.

I saw that you use django as a docker image for your dockerfile

The django image has been deprecated has you can see here : 

https://hub.docker.com/_/django

Do you want me to create a new issue and upgrade your Dockerfile image ?

**Comment by s-pratyush** [comment]
> @Pratyush-Saxena I will make a PR for this issue.
> 
> I saw that you use django as a docker image for your dockerfile
> 
> The django image has been deprecated has you can see here :
> 
> https://hub.docker.com/_/django
> 
> Do you want me to create a new issue and upgrade your Dockerfile image ?

@jphetphoumy yes you can creat a new issue
